"""
Database models for SCADA simulator and monitoring system.

All models use SQLAlchemy with async support.
"""
from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import Column, DateTime, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class Network(Base):
    """
    Stores network metadata.
    
    Each network represents an uploaded .inp file with its associated
    baseline data and generated readings.
    """
    __tablename__ = "networks"

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid4)
    name = Column(String(255), nullable=False)
    file_path = Column(String(500), nullable=False)
    uploaded_at = Column(DateTime, default=datetime.now, nullable=False)  # Use local time instead of UTC
    baseline_calculated_at = Column(DateTime, nullable=True)

    # Relationships
    readings = relationship("SCADAReading", back_populates="network")
    logs = relationship("SCADAGenerationLog", back_populates="network")
    baseline_data = relationship("BaselineData", back_populates="network")
    network_items = relationship("NetworkItem", back_populates="network")
    anomalies = relationship("Anomaly", back_populates="network")
    expected_values = relationship("ExpectedValue", back_populates="network")


class NetworkItem(Base):
    """
    Stores network topology items (junctions, pipes, tanks).
    
    This table stores the structure of the network for reference
    during simulation and monitoring.
    """
    __tablename__ = "network_items"

    id = Column(Integer, primary_key=True, autoincrement=True)
    network_id = Column(PGUUID(as_uuid=True), ForeignKey("networks.id"), nullable=False)
    item_type = Column(String(50), nullable=False)  # "junction", "pipe", "tank"
    item_id = Column(String(100), nullable=False)  # ID from .inp file
    properties = Column(Text)  # JSON string for additional properties

    # Relationships
    network = relationship("Network", back_populates="network_items")

    # Indexes
    __table_args__ = (
        Index("idx_network_items_network_id", "network_id"),
        Index("idx_network_items_type", "item_type"),
    )


class BaselineData(Base):
    """
    Stores baseline values for generating SCADA readings.
    
    Baseline values are calculated from an initial EPANET simulation
    and used as reference points for generating realistic sensor readings.
    """
    __tablename__ = "baseline_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    network_id = Column(PGUUID(as_uuid=True), ForeignKey("networks.id"), nullable=False)
    location_id = Column(String(100), nullable=False)  # Node or link ID
    location_type = Column(String(50), nullable=False)  # "junction", "pipe", "tank"
    sensor_type = Column(String(50), nullable=False)  # "pressure", "flow", "level"
    baseline_value = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.now, nullable=False)  # Use local time instead of UTC

    # Relationships
    network = relationship("Network", back_populates="baseline_data")

    # Indexes
    __table_args__ = (
        Index("idx_baseline_network_id", "network_id"),
        Index("idx_baseline_location_id", "location_id"),
        Index("idx_baseline_network_location", "network_id", "location_id"),
    )


class SCADAReading(Base):
    """
    Stores all SCADA sensor readings generated by the simulator.
    
    Each reading represents a sensor measurement at a specific time,
    with timestamp delays applied to simulate realistic transmission delays.
    """
    __tablename__ = "scada_readings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    network_id = Column(PGUUID(as_uuid=True), ForeignKey("networks.id"), nullable=False)
    timestamp = Column(DateTime, nullable=False)  # When reading was taken (with delay applied)
    sensor_id = Column(String(100), nullable=False)  # e.g., "PRESSURE_29"
    sensor_type = Column(String(50), nullable=False)  # "pressure", "flow", "level"
    value = Column(Float, nullable=False)  # Actual sensor reading value
    location_id = Column(String(100), nullable=False)  # Node or link ID
    created_at = Column(DateTime, default=datetime.now, nullable=False)  # Use local time instead of UTC

    # Relationships
    network = relationship("Network", back_populates="readings")

    # Indexes for query performance
    __table_args__ = (
        Index("idx_readings_network_id", "network_id"),
        Index("idx_readings_timestamp", "timestamp"),
        Index("idx_readings_sensor_id", "sensor_id"),
        Index("idx_readings_network_timestamp", "network_id", "timestamp"),
    )


class SCADAGenerationLog(Base):
    """
    Stores generation cycle logs for frontend display.
    
    Each log entry represents one generation cycle, showing how many
    readings were generated and which items were selected.
    """
    __tablename__ = "scada_generation_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    network_id = Column(PGUUID(as_uuid=True), ForeignKey("networks.id"), nullable=False)
    generation_timestamp = Column(DateTime, nullable=False)  # When generation cycle ran (real-time)
    readings_generated = Column(Integer, nullable=False)  # Number of readings generated
    junctions_selected = Column(Integer, nullable=False)  # Number of junctions selected (after data loss)
    pipes_selected = Column(Integer, nullable=False)  # Number of pipes selected (after data loss)
    tanks_selected = Column(Integer, nullable=False)  # Number of tanks selected (after data loss)
    created_at = Column(DateTime, default=datetime.now, nullable=False)  # Use local time instead of UTC

    # Relationships
    network = relationship("Network", back_populates="logs")

    # Indexes for query performance
    __table_args__ = (
        Index("idx_logs_network_id", "network_id"),
        Index("idx_logs_generation_timestamp", "generation_timestamp"),
        Index("idx_logs_network_timestamp", "network_id", "generation_timestamp"),
    )


class Anomaly(Base):
    """
    Stores detected anomalies from monitoring service.
    
    An anomaly is created when a SCADA reading deviates significantly
    from the expected value predicted by EPANET. This model is completely
    separate from SCADA simulator components - it only stores monitoring results.
    
    The monitoring service compares actual SCADA readings (from database)
    with expected values from EPANET Extended Period Simulation (EPS).
    When the deviation exceeds the configured threshold, an anomaly is created.
    
    Attributes:
        network_id: UUID of the network being monitored
        timestamp: When the anomaly was detected (real-time, not SCADA reading timestamp)
        sensor_id: Sensor identifier (e.g., "PRESSURE_29")
        sensor_type: Type of sensor ("pressure", "flow", "level")
        location_id: Network location ID (junction, pipe, or tank ID from .inp file)
        actual_value: Actual value from SCADA reading
        expected_value: Expected value from EPANET prediction
        deviation_percent: Percentage deviation: |actual - expected| / expected × 100
        threshold_percent: Threshold that was exceeded (pressure: 10%, flow: 15%, level: 5%)
        severity: Severity classification ("medium", "high", "critical")
            - medium: deviation between 1.0× and 1.5× threshold
            - high: deviation between 1.5× and 2.0× threshold
            - critical: deviation >= 2.0× threshold
        created_at: When record was created in database
    """
    __tablename__ = "anomalies"

    id = Column(Integer, primary_key=True, autoincrement=True)
    network_id = Column(PGUUID(as_uuid=True), ForeignKey("networks.id"), nullable=False)
    timestamp = Column(DateTime, nullable=False)  # When anomaly was detected (real-time)
    sensor_id = Column(String(100), nullable=False)  # e.g., "PRESSURE_29"
    sensor_type = Column(String(50), nullable=False)  # "pressure", "flow", "level"
    location_id = Column(String(100), nullable=False)  # Node or link ID
    actual_value = Column(Float, nullable=False)  # Actual value from SCADA reading
    expected_value = Column(Float, nullable=False)  # Expected value from EPANET
    deviation_percent = Column(Float, nullable=False)  # Percentage deviation
    threshold_percent = Column(Float, nullable=False)  # Threshold that was exceeded
    severity = Column(String(20), nullable=False)  # "medium", "high", "critical"
    created_at = Column(DateTime, default=datetime.now, nullable=False)  # Use local time instead of UTC

    # Relationships
    network = relationship("Network", back_populates="anomalies")

    # Indexes for query performance
    __table_args__ = (
        Index("idx_anomalies_network_id", "network_id"),
        Index("idx_anomalies_timestamp", "timestamp"),
        Index("idx_anomalies_severity", "severity"),
        Index("idx_anomalies_network_timestamp", "network_id", "timestamp"),
        Index("idx_anomalies_network_severity", "network_id", "severity"),
    )


class ExpectedValue(Base):
    """
    Stores EPANET-predicted values for historical analysis and digital twin.
    
    This model stores expected values computed by EPANET Extended Period
    Simulation (EPS) during monitoring. Values are stored every monitoring
    cycle to enable trend analysis, pattern detection, and model accuracy tracking.
    
    This is completely separate from SCADA simulator - it only stores
    EPANET predictions, not SCADA readings. The monitoring service queries
    SCADA readings from the database and compares them with these expected values.
    
    Attributes:
        network_id: UUID of the network
        timestamp: When prediction was made (real-time, synchronized with monitoring cycle)
        location_id: Network location ID (junction, pipe, or tank ID from .inp file)
        sensor_type: Type of sensor ("pressure", "flow", "level")
        expected_value: Predicted value from EPANET EPS
        eps_hour: EPANET simulation hour (0-24) when prediction was made
            This helps track the simulation state and ensures synchronization
        created_at: When record was created in database
    """
    __tablename__ = "expected_values"

    id = Column(Integer, primary_key=True, autoincrement=True)
    network_id = Column(PGUUID(as_uuid=True), ForeignKey("networks.id"), nullable=False)
    timestamp = Column(DateTime, nullable=False)  # When prediction was made (real-time)
    location_id = Column(String(100), nullable=False)  # Node or link ID
    sensor_type = Column(String(50), nullable=False)  # "pressure", "flow", "level"
    expected_value = Column(Float, nullable=False)  # Predicted value from EPANET
    eps_hour = Column(Float, nullable=False)  # EPANET simulation hour (0-24)
    created_at = Column(DateTime, default=datetime.now, nullable=False)  # Use local time instead of UTC

    # Relationships
    network = relationship("Network", back_populates="expected_values")

    # Indexes for query performance
    __table_args__ = (
        Index("idx_expected_network_id", "network_id"),
        Index("idx_expected_timestamp", "timestamp"),
        Index("idx_expected_location_id", "location_id"),
        Index("idx_expected_network_timestamp", "network_id", "timestamp"),
        Index("idx_expected_network_location", "network_id", "location_id"),
    )

