# Generated by Django 5.1.3 on 2024-11-14 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('prerequisite', models.CharField(blank=True, max_length=255, null=True)),
                ('co_requisite', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_hours', models.IntegerField()),
                ('lecture_hours', models.IntegerField()),
                ('lab_hours', models.IntegerField(blank=True, null=True)),
                ('semester', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=255)),
                ('model_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('office_no', models.CharField(max_length=20)),
                ('office_ext', models.CharField(max_length=20)),
                ('office_hours', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='academic.course')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_id', models.CharField(max_length=20, unique=True)),
                ('main_category', models.CharField(choices=[('knowledge', 'Knowledge'), ('intellectual_skills', 'Intellectual Skills'), ('practical_skills', 'Practical Skills'), ('competency', 'Competency')], max_length=20)),
                ('sub_category', models.CharField(max_length=20)),
                ('related_program_learning_objective', models.CharField(max_length=255)),
                ('teaching_method', models.CharField(choices=[('lecture', 'Lecture'), ('discussion', 'Discussion'), ('lab', 'Lab'), ('project', 'Project')], max_length=50)),
                ('assessment_method', models.CharField(choices=[('exam', 'Exam'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('project', 'Project')], max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='academic.course')),
            ],
        ),
    ]
